  
import { VisualizerPreset } from '@/types/visualizer';

export const defaultPresets: VisualizerPreset[] = [
  {
    id: 'spectrum-circle-perfect',
    name: 'Spectrum Circle - Perfect',
    description:
      'Perfect spectrum circle with smooth audio mapping and beautiful effects',
    category: 'ambient',
    visualizerType: 'spectrum-circle',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-accent-primary)',
      backgroundColor: '#0A141E',
      opacity: 1,
      saturation: 1.1,
      brightness: 0.95,
      contrast: 1,
      barWidth: 8,
      barSpacing: 2,
      barHeight: 1.3,
      cornerRadius: 2,
      animationSpeed: 0.8,
      decayRate: 0.95,
      bounceIntensity: 0.2,
      waveAmplitude: 20,
      waveFrequency: 0.6,
      glowIntensity: 0.8,
      blurAmount: 1,
      distortionAmount: 0,
      reflectionOpacity: 0.15,
      bloomIntensity: 0.6,
      particleCount: 50,
      particleSize: 2,
      particleSpeed: 0.5,
      particleLife: 4,
      particleGravity: 0.02,
    },
    audioMapping: {
      lowFreqMapping: 'radius',
      midFreqMapping: 'opacity',
      highFreqMapping: 'glow',
      volumeMapping: 'glowIntensity',
      beatMapping: 'rotation',
      lowFreqSensitivity: 1.5,
      midFreqSensitivity: 1.2,
      highFreqSensitivity: 1.0,
      volumeSensitivity: 1.3,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
  {
    id: 'particle-system-perfect',
    name: 'Particle System - Perfect',
    description:
      'Responsive particle system with perfect audio mapping and visual effects',
    category: 'intimate',
    visualizerType: 'particle-system',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-accent-primary)',
      backgroundColor: '#12101D',
      opacity: 1,
      saturation: 1.2,
      brightness: 0.9,
      contrast: 1.1,
      barWidth: 8,
      barSpacing: 2,
      barHeight: 1.3,
      cornerRadius: 4,
      animationSpeed: 1.0,
      decayRate: 0.9,
      bounceIntensity: 0.3,
      waveAmplitude: 30,
      waveFrequency: 0.8,
      glowIntensity: 0.7,
      blurAmount: 0.5,
      distortionAmount: 0,
      reflectionOpacity: 0.2,
      bloomIntensity: 0.5,
      particleCount: 150,
      particleSize: 2.5,
      particleSpeed: 1.2,
      particleLife: 2.5,
      particleGravity: 0.08,
    },
    audioMapping: {
      lowFreqMapping: 'particleCount',
      midFreqMapping: 'particleSpeed',
      highFreqMapping: 'glow',
      volumeMapping: 'overallOpacity',
      beatMapping: 'particleBurst',
      lowFreqSensitivity: 1.6,
      midFreqSensitivity: 1.3,
      highFreqSensitivity: 1.1,
      volumeSensitivity: 1.4,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
  {
    id: 'matrix-rain-perfect',
    name: 'Matrix Rain - Perfect',
    description:
      'Classic matrix rain with perfect audio responsiveness and visual effects',
    category: 'dark',
    visualizerType: 'matrix-rain',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-accent-primary)',
      backgroundColor: '#0D0D0D',
      opacity: 1,
      saturation: 1,
      brightness: 1,
      contrast: 1.2,
      barWidth: 12,
      barSpacing: 3,
      barHeight: 1.3,
      cornerRadius: 0,
      animationSpeed: 1.3,
      decayRate: 0.7,
      bounceIntensity: 0.6,
      waveAmplitude: 40,
      waveFrequency: 1.1,
      glowIntensity: 0.6,
      blurAmount: 0,
      distortionAmount: 0,
      reflectionOpacity: 0.4,
      bloomIntensity: 0.3,
      particleCount: 200,
      particleSize: 2,
      particleSpeed: 1.5,
      particleLife: 1.2,
      particleGravity: 0.15,
    },
    audioMapping: {
      lowFreqMapping: 'dropSpeed',
      midFreqMapping: 'dropCount',
      highFreqMapping: 'glow',
      volumeMapping: 'dropIntensity',
      beatMapping: 'flash',
      lowFreqSensitivity: 1.7,
      midFreqSensitivity: 1.4,
      highFreqSensitivity: 1.2,
      volumeSensitivity: 1.5,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
  {
    id: 'frequency-bars-perfect',
    name: 'Frequency Bars - Perfect',
    description:
      'Optimized frequency bars with perfect responsiveness and visual appeal',
    category: 'dark',
    visualizerType: 'frequency-bars',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-text-secondary)',
      backgroundColor: '#0D0D0D',
      opacity: 1,
      saturation: 1.1,
      brightness: 1.05,
      contrast: 1.1,
      barWidth: 8,
      barSpacing: 2,
      barHeight: 1.3,
      cornerRadius: 2,
      animationSpeed: 1.2,
      decayRate: 0.85,
      bounceIntensity: 0.6,
      waveAmplitude: 60,
      waveFrequency: 1.0,
      glowIntensity: 0.5,
      blurAmount: 0,
      distortionAmount: 0,
      reflectionOpacity: 0.3,
      bloomIntensity: 0.2,
      particleCount: 100,
      particleSize: 3,
      particleSpeed: 1.1,
      particleLife: 2.0,
      particleGravity: 0.1,
    },
    audioMapping: {
      lowFreqMapping: 'barHeight',
      midFreqMapping: 'barHeight',
      highFreqMapping: 'barHeight',
      volumeMapping: 'overallOpacity',
      beatMapping: 'colorFlash',
      lowFreqSensitivity: 1.4,
      midFreqSensitivity: 1.2,
      highFreqSensitivity: 1.0,
      volumeSensitivity: 1.3,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
  {
    id: 'liquid-wave-perfect',
    name: 'Liquid Wave - Perfect',
    description: 'Smooth liquid waves with perfect audio responsiveness',
    category: 'energetic',
    visualizerType: 'liquid-wave',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-accent-primary)',
      backgroundColor: '#1C1616',
      opacity: 1,
      saturation: 1.3,
      brightness: 1.1,
      contrast: 1.2,
      barWidth: 8,
      barSpacing: 2,
      barHeight: 1.3,
      cornerRadius: 8,
      animationSpeed: 1.1,
      decayRate: 0.6,
      bounceIntensity: 0.8,
      waveAmplitude: 80,
      waveFrequency: 1.2,
      glowIntensity: 0.6,
      blurAmount: 0,
      distortionAmount: 0.1,
      reflectionOpacity: 0.5,
      bloomIntensity: 0.4,
      particleCount: 150,
      particleSize: 4,
      particleSpeed: 1.5,
      particleLife: 1.5,
      particleGravity: 0.15,
    },
    audioMapping: {
      lowFreqMapping: 'waveAmplitude',
      midFreqMapping: 'waveFrequency',
      highFreqMapping: 'glow',
      volumeMapping: 'animationSpeed',
      beatMapping: 'scalePulse',
      lowFreqSensitivity: 1.8,
      midFreqSensitivity: 1.5,
      highFreqSensitivity: 1.3,
      volumeSensitivity: 1.6,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
  {
    id: 'waveform-perfect',
    name: 'Waveform - Perfect',
    description: 'Perfect waveform visualization with smooth audio mapping',
    category: 'intimate',
    visualizerType: 'waveform',
    visualParameters: {
      primaryColor: 'var(--color-accent-primary)',
      secondaryColor: 'var(--color-accent-secondary)',
      accentColor: 'var(--color-accent-primary)',
      backgroundColor: '#18161A',
      opacity: 1,
      saturation: 1.2,
      brightness: 0.9,
      contrast: 1.1,
      barWidth: 8,
      barSpacing: 2,
      barHeight: 1.3,
      cornerRadius: 6,
      animationSpeed: 1.0,
      decayRate: 0.85,
      bounceIntensity: 0.4,
      waveAmplitude: 60,
      waveFrequency: 0.9,
      glowIntensity: 0.6,
      blurAmount: 1,
      distortionAmount: 0,
      reflectionOpacity: 0.3,
      bloomIntensity: 0.3,
      particleCount: 80,
      particleSize: 2.5,
      particleSpeed: 0.7,
      particleLife: 2.5,
      particleGravity: 0.08,
    },
    audioMapping: {
      lowFreqMapping: 'amplitude',
      midFreqMapping: 'frequency',
      highFreqMapping: 'opacity',
      volumeMapping: 'bloomIntensity',
      beatMapping: 'colorFlash',
      lowFreqSensitivity: 1.5,
      midFreqSensitivity: 1.3,
      highFreqSensitivity: 1.1,
      volumeSensitivity: 1.2,
      beatSensitivity: 2.0,
    },
    createdAt: new Date(),
    isDefault: true,
  },
];

export const getPresetById = (id: string): VisualizerPreset | undefined => {
  return defaultPresets.find(preset => preset.id === id);
};

export const getPresetsByCategory = (category: string): VisualizerPreset[] => {
  return defaultPresets.filter(preset => preset.category === category);
};

export const getAllDefaultPresets = (): VisualizerPreset[] => {
  return [...defaultPresets];
};

export const getPerfectPresetForType = (
  type: string
): VisualizerPreset | undefined => {
  return defaultPresets.find(preset => preset.visualizerType === type);
};
